name: Build

on: [push, pull_request]

jobs:
  Build:
    name: ${{ matrix.platform.name }}
    runs-on: ${{ matrix.platform.os }}
    strategy:
      matrix:
        platform:
        - { name: Windows, os: windows-latest }
        - { name: Linux,   os: ubuntu-latest, flags: -GNinja }
        - { name: MacOS,   os: macos-latest }
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - run: python -m pip install -U pip
    - run: pip install meson ninja
    - run: meson setup build
    - run: meson compile -C build
